### ISSUE TITLE
Compatibilité Linux

### ISSUE THREAD

**Issue by TheDevKiller** [CubeConflict/Cube-Conflict#1]
Salut ! Ce serait possible d'ajouter la compatibilité pour Linux ? Je peux pas faire tourner le jeu avec Wine

**Comment by CubeConflict** [comment]
Salut, le code source est disponible, il est possible de le compiler pour Linux sans problèmes

**Comment by Goldenbrain1** [comment]
'engine/movie.cpp:14:12: fatal error: SDL_mixer.h: Aucun fichier ou dossier de ce type
   #include "SDL_mixer.h"
            ^~~~~~~~~~~~~
'
Oups
par contre il y a un ../include/SDL_mixer.h
Je remplace et voilà : 
'engine/../include/SDL_config.h:48:10: fatal error: SDL_config_minimal.h: Aucun fichier ou dossier de ce type
 #include "SDL_config_minimal.h"
          ^~~~~~~~~~~~~~~~~~~~~~
'
LOL, bon là je ne peux rien faire.
Apparemment c'est une configuration qui marche sur toutes les platformes au cas où une platforme inconnue compilerait le truc (genre moi avec mon linux, il n'y a pas de configuration SDL pour linux mentionné dans ton fichier de config), seulement tu as dû retirer ce fichier car il t'était inutile (sale windowsien ! :P )
Fillon rends la config minimale !

P.S : Pendant ce temps je vais essayer de trouver ce fichier directement sur internet

**Comment by TheDevKiller** [comment]
À ta place j'ouvrirais une autre issue
